### ISSUE TITLE
Dataset is missing

### ISSUE THREAD

**Issue by gachiemchiep** [jiaxue1993/pytorch-material-classification#1]
Hi @jiaxue1993 
The google search brought me here. 
Your dataset at http://jiaxueweb.com/database/GTOS_256.zip is missing.

**Comment by jiaxue-ai** [comment]
Hi @gachiemchiep 
Please check if you can download through README link in this git repo. Sorry for the inconvenience

**Comment by gachiemchiep** [comment]
Hi @jiaxue1993 Thanks man. i found it now
